version: '3'

services:
  recognizer:
    image: recognizer
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recognition
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./docker.env
    volumes:
      - ./src:/app
